# Generated by Django 6.0.5 on 2026-05-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuringProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('initial_tape', models.CharField(default='101100', max_length=255)),
                ('start_state', models.CharField(default='0', max_length=50)),
                ('blank_symbol', models.CharField(default='_', max_length=1)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
